
[package]
name = "aarch64-vmsa"
version = "0.1.0"
edition = "2024"

[dependencies]
paging = { git = "https://github.com/joe3925/paging", rev = "c8a6c2856981ca7079a7a238419a3d25bb20764c" }
portable-atomic = { version = "1.13.1", default-features = false }
strum = { version = "0.28.0", default-features = false, features = ["derive"] }
